# ===============================
#       SERVER
# ===============================
server:
  port: 8082



  # ===============================
  #       DATABASE
  # ===============================

spring:
  datasource:
    username: username_yourDb
    password: password
    url: jdbc:postgresql://localhost:5432/db_name

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true