POST http://localhost:8082/student/create
Content-Type: application/json

{
  "id": 4,
  "firstName" : "Jon",
  "surName" : "John",
  "middleName" : "Micky",
  "description":"scottish",
  "gender": "MALE",
  "studyStartDate": "02.02.2021",
  "studyFieldId": 2,
  "birthdate": "04.05.2004"
}

####


GET http://localhost:8082/student
Content-Type: application/json

####


GET http://localhost:8082/student/2
Content-Type: application/json
Image
